### ISSUE TITLE
All 404?

### ISSUE THREAD

**Issue by absolutelysimon** [tjwalch/django-livereload-server#11]
Tried installing the app on the django tutorial project. All pages go to a 404. When the middleware is commented out and runserver is used, the 404's disappear and obviously the livereload doesn't function. This is on Windows 7, python 3.6, django 1.10.5

**Comment by tjwalch** [comment]
Did you follow the instructions and run **both** `livereload` and `runserver`? Sounds to me like you are only running `./manage.py livereload`.

**Comment by absolutelysimon** [comment]
If I run python ./manage.py livereload, then python ./manage.py runserver I get the following error from runserver:
"Error importing module: 'No module named 'livereload.MIDDLEWARE' ' "

**Comment by tjwalch** [comment]
You obviously have problems following the instructions but this is not a support forum.

**Comment by absolutelysimon** [comment]
Huh, I thought I followed them to a T, but I could be wrong. I'm new to git, is there somewhere else I should be talking about support for this app?
