### ISSUE TITLE
"No module named livereload.MIDDLEWARE" on runserver

### ISSUE THREAD

**Issue by absolutelysimon** [tjwalch/django-livereload-server#12]
Install goes fine

./manage.py livereload executes without a problem

./manage.py runserver fails with "Error importing module: 'No module named 'livereload.MIDDLEWARE' ' "

**Comment by tjwalch** [comment]
Hey come on, please check your settings before spamming the issue tracker. That error is not from this module's code. Do you know how to check a traceback? I think you forgot that Python is case sensitive and wrote "MIDDLEWARE" in caps in your `MIDDLEWARE` setting.

**Comment by absolutelysimon** [comment]
Oh, sorry. That was indeed the error. I'm really new to git and I'm not sure what's considered acceptable. Is there somewhere else I should be posting this?

Bah, though now I can access the page but it won't live-reload when I change the template. I think I'm just gonna give up and go to sleep.
