### ISSUE TITLE
Is there a way to monitor related files (like static CSS) for changes as well?

### ISSUE THREAD

**Issue by palewire** [tjwalch/django-livereload-server#13]
I would love to be able to update a page when static files in the same app change, like CSS that is imported at the top of the template. Is this possible?

**Comment by tjwalch** [comment]
Yes just follow the instructions. Everything that is found by staticfiles will be monitored for livereload upon change.

**Comment by palewire** [comment]
Thanks. This doesn't have to become your concern, but in my use case I have a slightly non-standard configuration of Django that does not utilize `django.contrib.staticfiles`. If I wanted to add an ad hoc directory to be monitored in the same manner as the staticfiles are automatically monitored, would that be possible?

**Comment by palewire** [comment]
Is there some way the [livereload.js](https://github.com/tjwalch/django-livereload-server/blob/master/livereload/vendors/livereload.js) is filtering CSS and JS files that change to decide whether to reload the page? Would it be possible to have it reload after changes are made to any static files?

**Comment by tjwalch** [comment]
Read the instructions first please. What you are asking is already described there.

**Comment by palewire** [comment]
You mean the README? I don't see it there.

**Comment by tjwalch** [comment]
"Extra files and/or paths to watch for changes can be added as positional arguments" It's right there!  Please. This issue is closed now. Respect that maintainers are not here to interpret English for you.

**Comment by palewire** [comment]
Alrighty. I can file a separate bug report on how this doesn't work when you use django compressor inline, if you'd like.
