### ISSUE TITLE
404 is being thrown for all routes

### ISSUE THREAD

**Issue by dreamawakening** [tjwalch/django-livereload-server#17]
I've installed and configured this plugin. Whenever I access any route, it throws a 404. I've tested the same routes using `runserver` instead of `livereload` and they work fine.

I'm running `Django 2.0.1` and `Python 3.6.1`.

Here's my redacted `settings.py`:

```python
INSTALLED_APPS = [
    'livereload',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.postgres',
    'main.apps.MainConfig',
    'webpack_loader',
    'compressor',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'livereload.middleware.LiveReloadScript',
]
```

Let me know if you need anything else. Cheers

**Comment by tjwalch** [comment]
Please read the instructions before posting issues. Does it say run `livereload` _instead_ of `runserver`? No  it doesn't. How could that even work? You run `livereload` **in addition too** `runserver` of course. 

This tracker is for problems with the code, not your problems understanding how to use it. I find it rude to not read instructions properly and then blame the developer.

**Comment by dreamawakening** [comment]
Sorry, I made a careless mistake and will be more careful in the future. I wasn't trying to blame the developer, I submitted an issue because I thought it'd help.

**Comment by tjwalch** [comment]
No problem! Good luck with your Django development!
