### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by fennecinspace** [tjwalch/django-livereload-server#19]
i get 404 Not Found when accessing the localhost from the port using python manage.py livereload

**Comment by YPCrumble** [comment]
Would you re-read the documentation and let us know if there is a way that the documentation could have been made even more explicit than it already is so that you wouldn't have encountered the issue?

**Comment by fennecinspace** [comment]
@YPCrumble it works when i use runserver (i can see livereload.js in the head tag).. but it only shows the page,(normal django behavior)  when i save the page doesn't reload, how do i solve this ?

the documentation isn't clear at all 
it says, do:
pip install django-livereload-server
add the INSTALLED_APP and MIDDLEWARE then do runserver
and go to localhost:8000 .... but when i do that it doesn't reload when saving, nothing happens

please specify that you have to launch 2 servers 
do 
python manage.py livereload 
keep it running and in another console (terminal)
do
python manage.py runserver

**Comment by ddahan** [comment]
I have to agree with @logxseven, the doc is not explicit about the fact than `livereload` command should be run conccurently to `runserver`. I was thinking of it as a replacement too and this issue helped me understand what was wrong.
Please consider adding a sentence in the doc to explain this. Thanks.
