### ISSUE TITLE
Add option to only live reload certain file types

### ISSUE THREAD

**Issue by dreamawakening** [tjwalch/django-livereload-server#21]
I'm using `django-livereload-server` only for live reloading my templates. I use `webpack-dev-server` to hot reload my static assets (SCSS, JS etc).

It'd be great to have an option to only live reload certain assets (which in my case is templates).

**Comment by tjwalch** [comment]
Do you think the options `--static` and `--templates` would be enough? I can also imagine e g specifying certain paths to exclude.

**Comment by dreamawakening** [comment]
That'd be fine for my particular case, but I think it might be better if you could specify which static files you want to exclude.

For instance, someone down the road might want to serve images with Django, but other assets (like SCSS) with Webpack or something else.
