### ISSUE TITLE
Add option to change the hosts from 127.0.0.1

### ISSUE THREAD

**Issue by ghost** [tjwalch/django-livereload-server#3]
I had to hack my local copy in three places in order to change the client and server host names.

**Comment by tjwalch** [comment]
Someone made this kind of change in a [fork](https://github.com/Valian/django-livereload-server). Why don't you evaluate that and if it's good I can merge it.

**Comment by ghost** [comment]
This would be really useful, django-livereload-server is an awesome but forcing it to 127.0.0.1 means that I cannot use it in a container which is very useful.

**Comment by tjwalch** [comment]
Fixed in next release
