### ISSUE TITLE
ImportError: No module named apps

### ISSUE THREAD

**Issue by wxttt** [tjwalch/django-livereload-server#30]
I tried to use it with Django 1.6.4 but raise this error
`  File "/Users/wxttt/.virtualenvs/fitness/lib/python2.7/site-packages/livereload/management/commands/livereload.py", line 4, in <module>
    from django.apps import apps
ImportError: No module named apps`

**Comment by tjwalch** [comment]
Django 1.6 has reached it's end-of-life long ago. No modification to support such an old version will be made.
