### ISSUE TITLE
Latest release (supporting --ignore-file-extension) isn't on pypi (there is a workaround)

### ISSUE THREAD

**Issue by eternaldensity** [tjwalch/django-livereload-server#51]
When I installed with `pip install django-livereload-server`, --ignore-file-extension was not an available option for `python manage.py livereload`

To get the latest tag which does support --ingore-file-extension, I had to install from github with `pip install -e git+https://github.com/tjwalch/django-livereload-server.git@0.3.3#egg=django-livereload-server`

**Comment by tjwalch** [comment]
Version 0.4 now on pypi
