### ISSUE TITLE
New Path class isn't supported

### ISSUE THREAD

**Issue by fennecinspace** [tjwalch/django-livereload-server#55]
When using the new `Path` class in latest Django versions, static files aren't reloaded on save (they aren't watched) :

```
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = BASE_DIR / 'static'
```

Doing this on the other hand works :
```
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = os.path.join(BASE_DIR, 'static')
```

**Comment by tjwalch** [comment]
@fennecinspace I don't recognize the setting `STATIC_DIR`, is it something you use in `STATICFILES_DIRS`?

**Comment by fennecinspace** [comment]
@tjwalch 

Yes, `STATICFILES_DIRS = [ STATIC_DIR ]`
