### ISSUE TITLE
livereload.js  404 3172

### ISSUE THREAD

**Issue by Mecil9** [tjwalch/django-livereload-server#60]
"GET /127.0.0.1:35729/livereload.js HTTP/1.1" 404 3172
![image](https://user-images.githubusercontent.com/2948534/155280926-96977dbd-b8cc-4920-a528-9e11603186b3.png)
how to fix it?

![image](https://user-images.githubusercontent.com/2948534/155280980-66795e15-bb83-47fd-906f-f0a633be76c9.png)

**Comment by tjwalch** [comment]
Did you start the livereload server as clearly and explicitly described [here](https://github.com/tjwalch/django-livereload-server#usage)?
