### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by mikaraunio** [tjwalch/django-livereload-server#69]
Version 0.4.0 was released almost two years ago in December 2021, and multiple issues have been fixed since then. Would you be able to make a new release and publish it to PyPI?

**Comment by tjwalch** [comment]
Of course, thank you for the reminder.

**Comment by mikaraunio** [comment]
Thanks very much.

Just checking whether it's intentional that `__version__` and thus PyPI is 0.5, but the release is 0.4.1?
