### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by JeansReal** [tjwalch/django-livereload-server#8]
WARNINGS:
?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.

if the middleware 'livereload.middleware.LiveReloadScript', is on the new MIDDLEWARE settings then django trows: Unhandled exception in thread started by <function wrapper at 0x7fa9c7fbe050>

**Comment by tjwalch** [comment]
fixed
